export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  ORDER_MANAGER = 'ORDER_MANAGER',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  ANALYTICS_VIEWER = 'ANALYTICS_VIEWER'
}