export enum DevRole {
  SENIOR_DEVELOPER = 'SENIOR_DEVELOPER',
  JUNIOR_DEVELOPER = 'JUNIOR_DEVELOPER',
  DEVOPS_ENGINEER = 'DEVOPS_ENGINEER',
  QA_ENGINEER = 'QA_ENGINEER',
  SYSTEM_ARCHITECT = 'SYSTEM_ARCHITECT',
  SECURITY_ENGINEER = 'SECURITY_ENGINEER'
}